CREATE TABLE [dbo].[Guest]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [FirstName] NVARCHAR(100) NOT NULL, 
    [LastName] NVARCHAR(100) NULL, 
    [Email] VARCHAR(200) NOT NULL, 
    [Phone] NVARCHAR(100) NULL
)
